version: '3'

services:
    database:
        container_name: database
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker_mysql
            MYSQL_USER: user
            MYSQL_PASSWORD: mdp
        ports:
            - 3306
        volumes:
            - /data/mysql:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        depends_on:
            - database
        ports:
            - 8080:80
        environment:
            - PMA_HOST=database

    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8081:8080
